services:
  db:
    image: postgres:16-alpine
    container_name: ctms_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ctms
    ports:
      - "5499:5499"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
